### ISSUE TITLE
Feature: open source play.tailwindcss.com clone

### ISSUE THREAD

**Issue by WooodHead** [WindChat-Link/windchat-extension#1]
When previewing Tailwindcss, I wanted to open a full-screen editor and preview in a new window. After some searching, I found out that play.tailwindcss.com is not open-source. They initially released an open-source version, but later on, they stopped open-sourcing it. Well, I'll see if I can create something similar.

预览 Tailwindcss 时想在新窗口打开全屏编辑并预览，逛了一圈发现 play.tailwindcss.com 竟然不是开源的。最初版本开源了一个版本，后面就不开源了，好吧。。。

我看看能不能照着搞一个

> https://github.com/tailwindlabs/tailwindcss/discussions/2511

> https://github.com/tailwindlabs/tailwindcss-playground/issues/22

<img width="1084" alt="image" src="https://github.com/WindChat-Link/windchat-extension/assets/5668806/bbecba2a-8d92-417d-bddd-07e5ddb1fbd1">

<img width="1022" alt="image" src="https://github.com/WindChat-Link/windchat-extension/assets/5668806/ba75e360-ca37-4479-a930-973d5278bd0f">

**Comment by WooodHead** [comment]
First version:
https://github.com/WindChat-Link/windchat-tailwindcss-playground

![](https://github.com/WindChat-Link/windchat-tailwindcss-playground/blob/master/images/light.png?raw=true)

![](https://github.com/WindChat-Link/windchat-tailwindcss-playground/blob/master/images/dark.png?raw=true)

**Comment by WooodHead** [comment]
solved

**Comment by duolabmeng6** [comment]
兄弟代码还在吗 打不开了 望回复谢谢
